Repository masters2023-project-06-second-hand/be-a, pull requests merged in 2023-08, with the labels that each got.

#5 Feature/#4 공통작업
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/entity/Category.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/repository/CategoryJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/entity/Member.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/repository/MemberJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/entity/MemberRegion.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/request/ProductSaveRequestDto.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/utils/ProductStatus.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/entity/Region.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/repository/RegionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/CustomRuntimeException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CategoryException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CustomException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/MemberException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ProductException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/RegionException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/handler/GlobalExceptionHandler.java
  secondhand/src/main/resources/application-jpa.yml
  secondhand/src/main/resources/application-localDB.yml
  secondhand/src/main/resources/application.yml
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: ✨ feature

#7 #6 feat: 이미지 업로드 기능 구현
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/config/S3Config.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/controller/ImageController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/ImageFileResponseDto.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ImageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/FileUploadException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ImageException.java
  secondhand/src/main/resources/application-aws.yml
  secondhand/src/main/resources/application.yml
Labels: ✨ feature

#9 Feature/#8 상품 등록 시 이미지 update
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/CustomRuntimeException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CategoryException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CustomException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/FileUploadException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ImageException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/MemberException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ProductException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/RegionException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/handler/GlobalExceptionHandler.java
  secondhand/src/main/resources/application.yml
  secondhand/src/test/java/com/codesquad/secondhand/annotation/IntegrationTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
  secondhand/src/test/resources/schema.sql
  secondhand/src/test/resources/test-image.jpg
Labels: ✨ feature

#11 Feature/#10 상품 상세조회 기능 구현
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/entity/Member.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductDetailResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/Writer.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/utils/ProductStatus.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ProductException.java
  secondhand/src/main/resources/application.yml
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: ✨ feature

#17 Feature/#12 카테고리 목록 조회 구현
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/controller/CategoryController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/dto/response/CategoryResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/service/CategoryService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/category/controller/CategoryControllerTest.java
Labels: ✨ feature

#18 Feature/#16 상품 상태 수정 기능 구현
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/request/ProductUpdateRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/utils/ProductStatus.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: ✨ feature

#19 Feature/#13 상품 삭제
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🚦test, ✨ feature

#20 Feature/#14 be 이미지 삭제
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/controller/ImageController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/request/ImageDeleteRequestDto.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/response/ImageFileResponseDto.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
Labels: 🚦test, ✨ feature

#21 Feature/#15 상품 수정
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/request/ProductSaveRequestDto.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/handler/GlobalExceptionHandler.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🚦test, ✨ feature

#23 Feature/#22 리팩토링
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/service/CategoryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/controller/ImageController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/request/ImageDeleteRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/response/ImageFileResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/request/ProductSaveAndUpdateRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/main/resources/application-aws.yml
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: ♻️ refactor

#25 Feature/#24 spring security를 사용한 로그인 구현
  secondhand/.gitignore
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/config/SecurityConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/Jwt.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/JwtProvider.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/entity/Member.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/repository/MemberJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/domain/OAuthAttributes.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/domain/UserProfile.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuthService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/token/entity/Token.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/token/repository/TokenJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/CustomRuntimeException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/ErrorResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CategoryException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/CustomException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/FileUploadException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ImageException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/MemberException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/ProductException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/RegionException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/handler/GlobalExceptionHandler.java
  secondhand/src/main/resources/application-aws.yml
  secondhand/src/main/resources/application.yml
Labels: ✨ feature

#27 Feature/#26 회원가입 api
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/SignupRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/repository/MemberJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/entity/MemberRegion.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/repository/MemberRegionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/MemberException.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: ✨ feature

#31 Feature/#29 로그아웃 api 구현
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/common/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/util/RequestParser.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/controller/ImageController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/JwtProvider.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/SignupRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductDetailResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/RedisProperties.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/config/RedisConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/util/RedisUtil.java
  secondhand/src/main/resources/application-jpa.yml
  secondhand/src/main/resources/application-redis.yml
  secondhand/src/main/resources/application.yml
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/annotation/IntegrationTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/category/controller/CategoryControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🚦test, ✨ feature

#33 Chore/#32 yml 파일 암호화
  secondhand/.gitignore
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/config/S3Config.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/SignupRequest.java
  secondhand/src/main/resources/application-aws.yml
  secondhand/src/main/resources/application-jasypt.yml
  secondhand/src/main/resources/application-jwt.yml
  secondhand/src/main/resources/application-oauth.yml
  secondhand/src/main/resources/application.yml
Labels: 🔧chore
