Repository masters2023-project-06-second-hand/be-a, pull requests merged in 2023-09, with the labels that each got.

#50 Feature/#42 관심 상품들의 카테고리 목록 조회
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/controller/CategoryController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/controller/ReactionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/entity/Reaction.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/repository/ReactionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/category/controller/CategoryControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/reaction/controller/ReactionControllerTest.java
Labels: ✨ feature

#51 Feature/#39 카테고리별 상품 목록 조회
  secondhand/.gitignore
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/config/QuerydslConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/request/ProductSaveAndUpdateRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductFindAllResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Product.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/repository/ReactionJpaRepository.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
  secondhand/src/test/resources/schema.sql
Labels: ✨ feature

#52 Feature/#43 카테고리별 관심 상품 목록 조회
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/controller/ReactionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/reaction/controller/ReactionControllerTest.java
Labels: ✨ feature

#54 Feature/#44 내 지역 목록 추가
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/AddRegionRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/entity/MemberRegion.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/repository/MemberRegionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/RegionException.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
Labels: 🚦test, ✨ feature

#55 Feature/#45 내 지역 목록 삭제
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/RegionRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/repository/MemberRegionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
Labels: 🚦test, ✨ feature

#56 Feature/#46 내 기본 지역(대표지역) 설정변경
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/entity/Member.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/RegionException.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
Labels: 🚦test, ✨ feature

#57 Feature/#47 내 지역 목록 조회
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/RegionResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/Regions.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/repository/MemberRegionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/resources/schema.sql
Labels: 🚦test, ✨ feature

#58 Feature/#48 필터링 된 지역 목록 조회 페이징검색
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/controller/RegionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/dto/response/RegionSearchAndPageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/repository/RegionQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/controller/RegionControllerTest.java
Labels: 🚦test, ✨ feature

#60 Refactor/#59 api 리팩토링
  .gitignore
  secondhand/src/main/java/com/codesquad/secondhand/amazon/S3Uploader.java
  secondhand/src/main/java/com/codesquad/secondhand/common/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/util/RequestParser.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/service/CategoryQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/category/service/CategoryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/controller/ImageController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/dto/request/ImageDeleteRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/image/service/ImageService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/JwtProvider.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/RegionRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/request/SignupRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/MemberRegionResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/RegionResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/Regions.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/entity/MemberRegion.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/controller/ReactionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/entity/Reaction.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/repository/RegionQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/JwtException.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/handler/GlobalExceptionHandler.java
  secondhand/src/main/resources/application-jwt.yml
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/reaction/controller/ReactionControllerTest.java
Labels: ♻️ refactor

#64 #61 test: jwtFilter 테스트 작성
  secondhand/src/main/java/com/codesquad/secondhand/common/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/test/java/com/codesquad/secondhand/common/JwtFilterTest.java
Labels: 🚦test

#65 #63 test: 지역 Service 통합테스트 작성
  secondhand/src/test/java/com/codesquad/secondhand/annotation/ServiceIntegrationTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionServiceTest.java
Labels: 🚦test

#70 #69 test: 이미지 서비스 통합 테스트
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/entity/Image.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/service/ImageQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/service/ImageServiceTest.java
Labels: 🚦test

#72 #71 test: OAuth2SuccessHandler 단위 테스트 작성
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/domain/OAuthAttributes.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandlerTest.java
Labels: 🚦test

#75 Refactor/#74 cicd 리팩토링
  secondhand/src/main/java/com/codesquad/secondhand/common/CorsFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/config/FilterConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/config/SecurityConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
  secondhand/src/main/resources/application-oauth.yml
  secondhand/src/main/resources/application-prodDB.yml
  secondhand/src/main/resources/application-redis.yml
Labels: ♻️ refactor

#77 #76 refactor: Oauth 테스트 리팩토링
  secondhand/src/test/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandlerTest.java
Labels: 🚦test, ♻️ refactor

#80 #79 refactor: 이미지 테스트시 mock s3 서버를 사용하도록 변경
  secondhand/src/main/resources/application-jpa.yml
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/controller/ImageControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/image/service/ImageServiceTest.java
Labels: 🚦test, ♻️ refactor

#81 Feature/#67 멤버 service 통합테스트
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/service/MemberQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/service/MemberServiceTest.java
Labels: 🚦test, ♻️ refactor

#84 Test/#83 member region 서비스 통합 테스트
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionServiceTest.java
  secondhand/src/test/resources/schema.sql
Labels: 🚦test

#89 Feature/#87 사용자 정보 요청 기능
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/MemberInfoResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/resources/schema.sql
Labels: 🚦test, ✨ feature

#91 Refactor/#90 oauth 회원가입 응답 리팩토링
  secondhand/src/main/java/com/codesquad/secondhand/common/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/domain/Jwt.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/domain/JwtProvider.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/entity/Token.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/repository/TokenJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/dto/response/SignUpResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionQueryService.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/common/JwtFilterTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/service/MemberServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandlerTest.java
Labels: ♻️ refactor

#93 #92 refactor: OAuth2SuccessHandler 에서 jwtService 참조하도록 변경
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/oauth/service/OAuth2SuccessHandler.java
Labels: ♻️ refactor

#94 Feature/#88 지역 페이징검색 리팩토링
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/controller/RegionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/dto/response/RegionSearchAndPageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/dto/response/RegionsResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/repository/RegionQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/controller/RegionControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionServiceTest.java
Labels: ♻️ refactor

#96 #95 refactor: 리뷰 반영
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/dto/ReactionUpdateRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/entity/Reaction.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
Labels: ♻️ refactor

#99 Feature/#98 엑세스 토큰 재발급 api
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/domain/JwtProvider.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/dto/request/ReissueTokenRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/dto/response/ReissueTokenResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/repository/TokenJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/JwtException.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/jwt/service/JwtQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/jwt/service/JwtServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
Labels: 🚦test, ✨ feature

#100 Refactor#/97 filter 리팩토링 및 권한 추가
  secondhand/src/main/java/com/codesquad/secondhand/common/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/CommonFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/JwtFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/SignupTokenFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/WhiteListTokenCheckFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/WhiteListUri.java
  secondhand/src/main/java/com/codesquad/secondhand/config/FilterConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/config/SecurityConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/test/java/com/codesquad/secondhand/common/filter/JwtFilterTest.java
  secondhand/src/test/java/com/codesquad/secondhand/common/filter/SignupTokenFilterTest.java
  secondhand/src/test/java/com/codesquad/secondhand/common/filter/WhiteListTokenCheckFilterTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🚦test, ♻️ refactor

#102 #101 refactor : 지역 검색 권한 수정
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/CommonFilter.java
Labels: ♻️ refactor

#104 Feature/#103 채팅 초기 세팅
  secondhand/build.gradle
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/CommonFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/interceptor/StompInterceptor.java
  secondhand/src/main/java/com/codesquad/secondhand/config/WebSocketConfigurer.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/Message.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMember.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMessage.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatRoom.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMemberJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatRoomJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
  secondhand/src/test/resources/schema.sql
Labels: 🔧chore, ✨ feature

#107 Hotfix/#106 지역 목록 삭제시 기본지역 설정하도록 수정
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/service/MemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/controller/MemberRegionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionService.java
  secondhand/src/main/java/com/codesquad/secondhand/exception/errorcode/MemberException.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/controller/MemberRegionControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionServiceTest.java
Labels: 🥺 hotfix

#109 Feature/#108 product 전체 조회시 paging 기능 추가
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductFindAllResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/controller/ReactionController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/dto/response/RegionSearchAndPageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/region/service/RegionService.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/controller/RegionControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionServiceTest.java
Labels: ✨ feature

#111 Refactor/#110 be 리뷰 반영
  secondhand/src/main/java/com/codesquad/secondhand/domain/jwt/service/JwtService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/member/controller/MemberController.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/jwt/service/JwtQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/jwt/service/JwtServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/controller/MemberControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/service/MemberQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member/service/MemberServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/service/MemberRegionServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionQueryServiceTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/region/service/RegionServiceTest.java
Labels: ♻️ refactor

#112 Feature#/105 채팅 보내기 api 구현
  secondhand/src/main/java/com/codesquad/secondhand/common/interceptor/StompInterceptor.java
  secondhand/src/main/java/com/codesquad/secondhand/config/WebSocketConfigurer.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/MessageRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMember.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMessage.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatRoom.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/redis/ChatMember.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMemberJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMemberRedisRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/util/RedisUtil.java
  secondhand/src/main/resources/application-redis.yml
  secondhand/src/test/resources/schema.sql
Labels: ✨ feature

#114 Feature#/113 stomp command disconnect 시 처리 기능 구현
  secondhand/src/main/java/com/codesquad/secondhand/common/interceptor/StompInterceptor.java
  secondhand/src/main/java/com/codesquad/secondhand/common/util/RequestParser.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMemberRedisRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
Labels: ✨ feature

#120 Infra/#116 cicd
  .github/workflows/auto-deploy.yml
  nginx/Dockerfile
  nginx/nginx.conf
  secondhand/Dockerfile
  secondhand/src/main/resources/application-oauth.yml
  secondhand/src/main/resources/application-redis.yml
Labels: 🛠️ infra

#121 Feature#/115 채팅방 생성 채팅 참여정보 엔티티 생성
  secondhand/src/main/java/com/codesquad/secondhand/common/interceptor/StompInterceptor.java
  secondhand/src/main/java/com/codesquad/secondhand/common/util/RequestParser.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/request/ChatRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/request/MessageRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatMessageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatProductResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomDetailsResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMessage.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatRoom.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/redis/RedisChatMember.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMemberRedisRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatRoomJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/RedisChatMemberQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/RedisChatMemberService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/test/resources/schema.sql
Labels: ✨ feature

#123 Feature/#122 채팅방 접속 및 메시지 전송 시 읽음 상태 기능 구현 및 채팅방 조회 기능 구현
  secondhand/src/main/java/com/codesquad/secondhand/common/interceptor/StompInterceptor.java
  secondhand/src/main/java/com/codesquad/secondhand/config/WebSocketConfigurer.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/entity/ChatMessage.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/RedisChatMemberService.java
  secondhand/src/test/resources/schema.sql
Labels: ✨ feature

#127 #126 hotfix: whiteList 수정 및 스키마 수정
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/CommonFilter.java
  secondhand/src/test/resources/schema.sql
Labels: 🥺 hotfix

#130 #128 test: 채팅방 조회 테스트 작성
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/request/MessageRequest.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/chat/controller/ChatControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/controller/MemberRegionControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🚦test

#132 #131 test: 채팅방 입장 테스트 작성
  secondhand/src/test/java/com/codesquad/secondhand/domain/chat/controller/ChatControllerTest.java
Labels: 🚦test

#135 #134 feat: 조회수 기능 구현
  secondhand/src/main/java/com/codesquad/secondhand/SecondhandApplication.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/WhiteListTokenCheckFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/config/RedisConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/util/RedisUtil.java
Labels: ✨ feature

#141 #140 hotfix: 상품상세조회 response 수정
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductDetailResponse.java
Labels: 🥺 hotfix

#142 #138 feat : 채팅방 목록조회 api 구현
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomListResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomMessageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomOpponentResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomProductResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatRoomJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
Labels: ✨ feature

#143 [be] dev 변경사항 배포
  secondhand/src/main/java/com/codesquad/secondhand/SecondhandApplication.java
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/WhiteListTokenCheckFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/controller/ChatController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/request/MessageRequest.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomListResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomMessageResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomOpponentResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/dto/response/ChatRoomProductResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatMessageQueryRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/repository/ChatRoomJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/chat/service/ChatService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/controller/ProductController.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductDetailResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/dto/response/ProductStatResponse.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/repository/ProductJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/repository/ReactionJpaRepository.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionQueryService.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/reaction/service/ReactionService.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/config/RedisConfig.java
  secondhand/src/main/java/com/codesquad/secondhand/redis/util/RedisUtil.java
  secondhand/src/test/java/com/codesquad/secondhand/BaseControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/chat/controller/ChatControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/member_region/controller/MemberRegionControllerTest.java
  secondhand/src/test/java/com/codesquad/secondhand/domain/product/controller/ProductControllerTest.java
Labels: 🛠️ infra

#144 hotfix: 상품 상세조회시 memberId null(비회원) 인경우 처리
  secondhand/src/main/java/com/codesquad/secondhand/common/filter/CommonFilter.java
  secondhand/src/main/java/com/codesquad/secondhand/common/util/RequestParser.java
  secondhand/src/main/java/com/codesquad/secondhand/domain/product/service/ProductService.java
Labels: 🛠️ infra
